language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t shioncoder/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shioncoder/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucker_name: "elasticbeanstalk-ap-southeast-1-335268551950"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: "Encrypted <access-key-id>=AKIAU4D4QDUHB36ISA4V"
  secret_access_key: 
    secure: "Encrypted <secret-access-key>=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"